// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByzTe798v6Y-sdKsXjFz8II2k3AvvkHkQ',
    appId: '1:296742874642:web:570e9edc372765154232cb',
    messagingSenderId: '296742874642',
    projectId: 'dyooni-ea39a',
    authDomain: 'dyooni-ea39a.firebaseapp.com',
    storageBucket: 'dyooni-ea39a.firebasestorage.app',
    measurementId: 'G-VB1PW6PCZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-H3eO7zD1BAzY7OZbUTmLsCJEr1K_hc',
    appId: '1:296742874642:android:ed6832a45c57be1d4232cb',
    messagingSenderId: '296742874642',
    projectId: 'dyooni-ea39a',
    storageBucket: 'dyooni-ea39a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR-JWF_HzwsE-_Gd1dAqyS8Z4MGL91LEE',
    appId: '1:296742874642:ios:f0fb67d84abe039e4232cb',
    messagingSenderId: '296742874642',
    projectId: 'dyooni-ea39a',
    storageBucket: 'dyooni-ea39a.firebasestorage.app',
    iosBundleId: 'com.aqdev.dyooni.dyooni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR-JWF_HzwsE-_Gd1dAqyS8Z4MGL91LEE',
    appId: '1:296742874642:ios:f0fb67d84abe039e4232cb',
    messagingSenderId: '296742874642',
    projectId: 'dyooni-ea39a',
    storageBucket: 'dyooni-ea39a.firebasestorage.app',
    iosBundleId: 'com.aqdev.dyooni.dyooni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByzTe798v6Y-sdKsXjFz8II2k3AvvkHkQ',
    appId: '1:296742874642:web:acd16642cb5103294232cb',
    messagingSenderId: '296742874642',
    projectId: 'dyooni-ea39a',
    authDomain: 'dyooni-ea39a.firebaseapp.com',
    storageBucket: 'dyooni-ea39a.firebasestorage.app',
    measurementId: 'G-ZZNXEQVH3D',
  );
}
